### ISSUE TITLE
Error when trying to give some book

### ISSUE THREAD

**Issue by WRChicken** [MassiveCraft/MassiveBooks#6]
Hi,
I got an error when I'm trying to use the command : /book give player amount title

Console :
22.08 23:41:35 [Server] INFO ... 14 more
22.08 23:41:35 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:631) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:578) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:599) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivebooks.cmd.CmdBookGive.perform(CmdBookGive.java:61) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.util.InventoryUtil.roomLeft(InventoryUtil.java:425) ~[?:?]
22.08 23:41:35 [Server] INFO at com.massivecraft.massivecore.util.InventoryUtil.cloneInventory(InventoryUtil.java:328) ~[?:?]
22.08 23:41:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryPlayer.setHelmet(CraftInventoryPlayer.java:105) ~[spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:40) ~[spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryPlayer.getHolder(CraftInventoryPlayer.java:174) ~[spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInventory.getOwner(PlayerInventory.java:46) ~[spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO Caused by: java.lang.NullPointerException
22.08 23:41:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
22.08 23:41:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-BT42_1.8.8_08.02.jar:git-Spigot-d97e08b-880a532]
22.08 23:41:35 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:102) ~[?:?]
22.08 23:41:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'book give WrChicken 100 Guide du Claim' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(book)
22.08 23:41:35 [Server] ERROR null

**Comment by oloflarsson** [comment]
Update Spigot!
