### ISSUE TITLE
java.lang.IllegalArgumentException: Chests must have a size that is a multiple of 9!

### ISSUE THREAD

**Issue by SmallSansSerif** [MassiveCraft/MassiveBooks#8]
http://pastebin.com/LFFLrxS1

**Comment by oloflarsson** [comment]
Thank you. This should be fixed now. I will release 2.8.9 today.

**Comment by SmallSansSerif** [comment]
I don't get this error now but having a problem getting the server books on first joins. Should I open up another ticket or am I doing something wrong. 

It doesn't look like I need a perm to do this. Also if I delete a user out of the world playerdata folder shouldn't it treat them as a new player and give server books? Or do you check somewhere else for a new player?
